Now the validation works for me, your turn Andro

diff --git a/Config b/Config
--- a/Config
+++ b/Config
@@ -7,7 +7,7 @@
 #######################################################
 
 HOMEDIR="${HOME}"
-ISNUM="^[0-9]+$"
+ISNUM="^[1-9][0-9]*\$"
 
 # Variables we need to send to configure
 INSTALLDIR="${HOME}/x4"
@@ -93,15 +93,24 @@ while [ "${ok}" -eq 0 ] ; do
     fi
 
     if [ "${INPUT}" ] ; then
-        if [[ "$INPUT" =~ $ISNUM && "$INPUT" -gt 100 && "$INPUT" -lt "$MAXCONNS" ]] ; then
-            if [ "$INPUT" != "$MAXCONNS" ] ; then
-                CHG_MAXCONNS="y"
-                MAXCONNS=$INPUT
-            fi
-            break
-        else
-            echo "Invalid input. Max connections must be a valid number and between 100 and $MAXCONNS"
+        echo "$INPUT" | grep -q "$ISNUM"
+        if [ $? -ne 0 ] ; then
+            echo "Invalid input. Max connections must be a valid number"
+            continue
         fi
+        if [ "$INPUT" -lt 100 ] ; then
+            echo "Invalid input. Max connections must be above 100"
+            continue
+        fi
+        if [ "$INPUT" -gt "$MAXCONNS" ] ; then
+            echo "Invalid input. Max connections must be below $MAXCONNS"
+            continue
+        fi
+        if [ "$INPUT" != "$MAXCONNS" ] ; then
+            CHG_MAXCONNS="y"
+            MAXCONNS=$INPUT
+        fi
+        break
     fi
 done
 
