Work in progress

diff --git a/Config b/Config
--- a/Config
+++ b/Config
@@ -7,7 +7,8 @@
 #######################################################
 
 HOMEDIR="${HOME}"
-ISNUM="^[1-9][0-9]*\$"
+ISNUM="^[1-9][0-9]*$"
+YN="^([Yy]([Ee][Ss])?|[Nn]([Oo])?)+$"
 
 # Variables we need to send to configure
 INSTALLDIR="${HOME}/x4"
@@ -126,10 +127,19 @@ while [ "${ok}" -eq 0 ] ; do
         INPUT=$DEBUGMODE
         break
     fi
-    if [ "$INPUT" != "$DEBUGMODE" ] ; then
-        CHG_DEBUGMODE="y"
+
+    if [ "${INPUT}" ] ; then
+        echo "$INPUT" | grep -q "$YN"
+        if [ $? -ne 0 ] ; then
+            echo "Invalid input. Must be yes (y) or no (n)."
+            continue
+        fi
+        if [ "$INPUT" != "$DEBUGMODE" ] ; then
+            CHG_DEBUGMODE="y"
+            DEBUGMODE=$INPUT
+        fi
+        break
     fi
-    /* NEED to validate $INPUT is either yes, y, no or n, if it is then set DEBUGMODE=$INPUT and set ok=1 */
 done
 
 ####
